// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBinqL6jZYlHRBfFSdNh5rscLNCubOaZoA',
    appId: '1:266456052663:web:7119729109f8298622ae32',
    messagingSenderId: '266456052663',
    projectId: 'hello-dost-92afc',
    authDomain: 'hello-dost-92afc.firebaseapp.com',
    storageBucket: 'hello-dost-92afc.firebasestorage.app',
    measurementId: 'G-5JKPYWFPMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJYRUvF2bkcbCuMn14-muXEdeiBWuySKQ',
    appId: '1:266456052663:android:554c128662cdd88422ae32',
    messagingSenderId: '266456052663',
    projectId: 'hello-dost-92afc',
    storageBucket: 'hello-dost-92afc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHvuXOuVZZqTO23KOn8iiDmDCzG2w6jy0',
    appId: '1:266456052663:ios:f0b00e7cc91beccb22ae32',
    messagingSenderId: '266456052663',
    projectId: 'hello-dost-92afc',
    storageBucket: 'hello-dost-92afc.firebasestorage.app',
    iosBundleId: 'com.example.zeeGoo',
  );
}
