// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB85q2AWWZPwInlZOf2E1eYZFz-A4OD1ZM',
    appId: '1:608464110787:web:a911c1f087eda814138e76',
    messagingSenderId: '608464110787',
    projectId: 'zee-goo',
    authDomain: 'zee-goo.firebaseapp.com',
    storageBucket: 'zee-goo.firebasestorage.app',
    measurementId: 'G-1JED76V3WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe2V6Uf9VYoggpuGQ1fL-3TXTCSZjHC0I',
    appId: '1:608464110787:android:883bbadb0e74df94138e76',
    messagingSenderId: '608464110787',
    projectId: 'zee-goo',
    storageBucket: 'zee-goo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfaHVdEjmUWhqqMnIRMMXSNxUwWD1nMVQ',
    appId: '1:608464110787:ios:a92453686ce19af4138e76',
    messagingSenderId: '608464110787',
    projectId: 'zee-goo',
    storageBucket: 'zee-goo.firebasestorage.app',
    iosBundleId: 'com.example.zeeGoo',
  );
}
